-- Lab Task # 01 (Schema Definition):
-- i)
CREATE TABLE ACCOUNT (
    ACCOUNT_NO CHAR(10),
    BALANCE NUMBER NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY(ACCOUNT_NO),
    CONSTRAINT ACCOUNT_BLNC_CHK CHECK(BALANCE>0)
);

--ii)
CREATE TABLE CUSTOMER (
    CUSTOMER_NO CHAR(5),
    CUSTOMER_NAME VARCHAR2(20) NOT NULL,
    CUSTOMER_CITY VARCHAR2(10),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_NO)
);

-- iii)

CREATE TABLE DEPOSITOR (
    ACCOUNT_NO CHAR(5),
    CUSTOMER_NO CHAR(5),
    CONSTRAINT  DEPOSITOR_PK PRIMARY KEY(ACCOUNT_NO,CUSTOMER_NO)
);

-- Lab Task # 02 (Schema Modification):

